server:
  tomcat:
    threads:
      max: ${MAX}
      min-spare: ${MIN_SPARE}
    max-connections: ${MAX_CONNECTIONS}
    accept-count: ${ACCEPT_COUNT}
    connection-timeout: ${CONNECTION_TIMEOUT}
  port: ${PORT}

custom:
  url: ${URL}
