spring:
  jpa:
    hibernate.dialect: ${HIBERNATE_DIALECT}
    hibernate:
      ddl-auto: ${DDL_AUTO}
    properties:
      hibernate:
        dialect: ${DIALECT}
        default_batch_fetch_size: ${DEFAULT_BATCH_FETCH_SIZE}
        show_sql: true
        format_sql: true
    open-in-view: false
    show-sql: true
  datasource:
    driver-class-name: ${DRIVER_CLASS_NAME}
    url: ${URL}
    username: ${USERNAME}
    password: ${PASSWORD}
server:
  port: ${PORT}
